@baseURL = http://localhost:3001/api/v1/bucketList

###
POST {{baseURL}}
Content-Type: application/json

{
    "bucketList":"Combodia",
    "money":199,
    "type":"entry"

}

###
GET {{baseURL}}


###
PATCH  {{baseURL}}
Content-Type: application/json

{
    "_id":"670e1c19534f10f1d7d93115",
    "bucketList":"Europe",
    "money":3600,
    "type":"bad"
}

###
DELETE {{baseURL}}/67071fc186437997e6955936
Content-Type: application/json



